apiVersion: apps/v1
kind: Deployment
metadata:
  name: nblotti-achilleus
  labels:
    app: nblotti_achilleus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nblotti_achilleus
  template:
    metadata:
      labels:
        app: nblotti_achilleus
    spec:
      containers:
        - name: nblotti
          image: nblotti/achilleus:v0.0.15
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
